### ISSUE TITLE
Error on setting parameters

### ISSUE THREAD

**Issue by Miroqil** [RafWu/RansomWatch#3]
In function 
<BOOLEAN DeletionTrigger()>
<ULONGLONG numOfFilesProtected = Globals::Instance->addNumOfDirsProtected(0);>
I think need change it to 
addNumOfDirsProtected --> need to change to -->addNumOfFilesProtected

**Comment by RafWu** [comment]
> In function
> <BOOLEAN DeletionTrigger()>
> addNumOfDirsProtected(0);>
> I think need change it to
> addNumOfDirsProtected --> need to change to -->addNumOfFilesProtected

Thx for letting us know, I changed the setting.
